name: CI/CD Pipeline

on: # Define the events that will trigger the pipeline
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

permissions: #
  contents: read
  pages: write
  id-token: write

jobs: # Define the jobs that will be executed
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Define the URL of the deployed web app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages # Deploy the web app to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use the peaceiris/actions-gh-pages action
        with:
          github_token: ${{ secrets.WEB_GITHUB_TOKEN }}
          publish_dir: ./github-action-web # Directory to deploy
